services:
  - type: web
    name: reviewme-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: cd dist && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
