services:
  - type: web
    name: reviewme-api
    runtime: node
    nodeVersion: 18.x
    buildCommand: |
      npm install
      npm run build
    startCommand: cd dist && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
