openapi: 3.0.0
info:
  title: Product Review API
  version: 1.0.0
  description: API for managing products and their reviews

servers:
  - url: http://localhost:3000/api
    description: Development server

paths:
  /products:
    get:
      summary: Get all products
      description: Retrieve a list of all products
      responses:
        "200":
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

    post:
      summary: Create a new product
      description: Create a new product in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductInput"
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

  /products/search:
    get:
      summary: Search products
      description: Search products by name
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Search query
      responses:
        "200":
          description: List of matching products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

  /products/{id}:
    get:
      summary: Get product by ID
      description: Retrieve a single product by its ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Product ID
      responses:
        "200":
          description: Product details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found

  /products/{productId}/reviews:
    get:
      summary: Get product reviews
      description: Retrieve all reviews for a specific product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: Product ID
      responses:
        "200":
          description: List of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Review"

    post:
      summary: Add product review
      description: Add a new review for a specific product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: Product ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReviewInput"
      responses:
        "201":
          description: Review created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Review"

  /products/{productId}/reviews/{id}:
    put:
      summary: Update review
      description: Update an existing review
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: Product ID
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Review ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReviewInput"
      responses:
        "200":
          description: Review updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Review"

    delete:
      summary: Delete review
      description: Delete an existing review
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: Product ID
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Review ID
      responses:
        "204":
          description: Review deleted successfully

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ProductInput:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number

    Review:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        rating:
          type: number
        comment:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ReviewInput:
      type: object
      required:
        - rating
      properties:
        rating:
          type: number
          minimum: 1
          maximum: 5
        comment:
          type: string
